### ISSUE TITLE
Sex of subjects

### ISSUE THREAD

**Issue by Tian-A-Tan** [timvanderzee/human-walking-biomechanics#2]
Hello,

Thank you for sharing your data. Could you provide sex of each subject? This information is not covered by the table 1 of your publication. 

Thank you!

**Comment by timvanderzee** [comment]
Hi, 

Thanks for your interest in the dataset. Unfortunately I do not possess this information, as this was not part of the questionnaire completed by participants. Sorry I could not help you. 

Best,
Tim
